/** types/autocomplete **/

export const types = {
  AUTOCOMPLETE_UPDATE_MODE: 'AUTOCOMPLETE_UPDATE_MODE',
  AUTOCOMPLETE_UPDATE_INPUT: 'AUTOCOMPLETE_UPDATE_INPUT',
  AUTOCOMPLETE_REQUEST: 'AUTOCOMPLETE_REQUEST',
  AUTOCOMPLETE_SUCCESS: 'AUTOCOMPLETE_SUCCESS',
  AUTOCOMPLETE_FAILURE: 'AUTOCOMPLETE_FAILURE'
} 
